#!/usr/bin/perl

use strict;
use warnings;
use File::Basename;

print <<EOF;
#!/bin/sh

declare -A color
declare -A pcolor

EOF

my %general = (
  'reset' => 0,
  'fgDefault' => 39,
  'bgDefault' => 49,
  'bold' => 1,
  'resetBold' => 22,
  'underline' => 4,
  'resetUnderline' => 24,
  'blink' => 5,
  'resetBlink' => 25,
  'reverse' => 7,
  'resetReverse' => 27
);
my @indices;
foreach (sort keys %general) {
  print "color[$_]='\\e[$general{$_}m'\n";
  push @indices, $_;
}
print "\n";

my @color_names = ('black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'gray');
for (my $i = 0; $i < @color_names; ++$i) {
  my $color_name = ucfirst $color_names[$i];
  my $name_fg="fg${color_name}";
  my $name_fgLight="fgLight${color_name}";
  my $name_bg="bg${color_name}";
  my $name_bgLight="bgLight${color_name}";

  # change Black/LightBlack and Gray/LightGray
  # to Black/DarkGray and LightGray/White
  if ($i == 0) {
    $name_fgLight = "fgDarkGray";
    $name_bgLight = "bgDarkGray";
  }
  if ($i == 7) {
    $name_fg="fgLightGray";
    $name_fgLight="fgWhite";
    $name_bg="bgLightGray";
    $name_bgLight="bgWhite";
  }

  print <<EOF;
color[fg$i]='\\e[3${i}m'
color[$name_fg]='\\e[3${i}m'
color[$name_fgLight]='\\e[9${i}m'
color[bg$i]='\\e[4${i}m'
color[$name_bg]='\\e[4${i}m'
color[$name_bgLight]='\\e[10${i}m'

EOF
  push @indices, $name_fg, $name_fgLight, $name_bg, $name_bgLight, "fg$i", "bg$i";
}

print "# prompt colors: color codes wrapped in \\[...\\] for use in PS1 etc.\n";

foreach my $index (sort @indices) {
  print "pcolor[$index]=\"\\[\${color[$index]}\\]\"\n";
}
