#!/usr/bin/perl

use strict;
use warnings;
use File::Basename;

print "#!/bin/sh\n\n";

my %general = (
  'reset' => 0,
  'fgDefault' => 39,
  'bgDefault' => 49,
  'bold' => 1,
  'resetBold' => 22,
  'underline' => 4,
  'resetUnderline' => 24,
  'blink' => 5,
  'resetBlink' => 25,
  'reverse' => 7,
  'resetReverse' => 27
);
my @color_variables;
foreach (sort keys %general) {
  print "color_$_='\\e[$general{$_}m'\n";
  push @color_variables, "color_$_";
}
print "\n";

my @color_names = ('black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'gray');
for (my $i = 0; $i < @color_names; ++$i) {
  my $color_name = ucfirst $color_names[$i];
  my $name_fg="color_fg${color_name}";
  my $name_fgLight="color_fgLight${color_name}";
  my $name_bg="color_bg${color_name}";
  my $name_bgLight="color_bgLight${color_name}";

  # change Black/LightBlack and Gray/LightGray
  # to Black/DarkGray and LightGray/White
  if ($i == 0) {
    $name_fgLight = "color_fgDarkGray";
    $name_bgLight = "color_bgDarkGray";
  }
  if ($i == 7) {
    $name_fg="color_fgLightGray";
    $name_fgLight="color_fgWhite";
    $name_bg="color_bgLightGray";
    $name_bgLight="color_bgWhite";
  }

  print <<EOF;
$name_fg='\\e[3${i}m'
$name_fgLight='\\e[9${i}m'
$name_bg='\\e[4${i}m'
$name_bgLight='\\e[10${i}m'
EOF
  push @color_variables, $name_fg, $name_fgLight, $name_bg, $name_bgLight;
}

print "\n";
print "# prompt colors: color codes wrapped in \\[...\\] for use in PS1 etc.\n";

foreach my $color_variable (@color_variables) {
  print "p$color_variable=\"\\[\$$color_variable\\]\"\n";
}
